name: pipeline-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-edger
  - samtools
  - salmon
  - pip:
    - matplotlib
    - seaborn
    - cython
    - numpy
    - numba
    - scipy
    - scikit-learn
    - statsmodels
    - pandas
