channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.6.0
  - illumina-interop
  - samtools
  - bwa
  - star
  - bedtools
  - r-base
  - bioconductor-deseq2
  - bioconductor-edger
  - pip
  - pip:
    - matplotlib
    - seaborn
    - cython
    - numpy
    - numba
    - scipy
    - scikit-learn
    - statsmodels
    - pandas
